apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: developer-sa
      containers:
        - name: webapp
          image: leofvo/demo-k8s-pentesting:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
  - apiGroups: ['']
    resources:
      - pods
      - serviceaccounts
    verbs:
      - list
      - get
  - apiGroups: ['rbac.authorization.k8s.io']
    resources:
      - rolebindings
      - clusterrolebindings
    verbs:
      - list
      - get
  - apiGroups: ['']
    resources:
      - pods/exec
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-to-sa
subjects:
  - kind: ServiceAccount
    name: developer-sa
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
